import { ICustomBotClient } from '../interfaces/custom-bot';
import { IUserLevel } from '../interfaces/user';
import { CustomBotClient } from '../classes/custom-bot-client.class';
import { NotFoundException } from '../classes/errors';

export interface IConfigExpUser {
    expRatioByDefaultRole: number;
    expPerCharacter: number;
    neededExpToTheNextLevel: number;
    maxLevel: number;
}

export class LevelController {
    readonly customBotClient: CustomBotClient;

    private readonly configExp: IConfigExpUser = {
        expRatioByDefaultRole: 1.0,
        expPerCharacter: 80,
        neededExpToTheNextLevel: 5000,
        maxLevel: 100,
    };

    constructor(props: ICustomBotClient) {
        this.customBotClient = props.customBotClient;
    }

    async generateExpBasedOnRoleByMessageLength(
        messageLength: number
    ): Promise<number> {
        if (messageLength <= 0) {
            throw new NotFoundException('required message length');
        }

        const generateExpBasedOnStringLength =
            messageLength * this.configExp.expPerCharacter;

        const generateExp =
            Math.floor(
                generateExpBasedOnStringLength *
                    this.configExp.expRatioByDefaultRole
            ) / 100;

        return generateExp;
    }

    async giveExpToUserByMessage({ user, messageLength }: IUserLevel) {
        try {
            const userExpGenerated =
                await this.generateExpBasedOnRoleByMessageLength(messageLength);

            console.log(
                `[level:controller:generateXP] To user <${user.discordName}:${user.discordId}:${userExpGenerated} Exp Generated By Default Role (Ratio: ${this.configExp.expRatioByDefaultRole})>`
            );

            if (userExpGenerated) {
                user.xp += Number(userExpGenerated.toFixed(2));
            }

            if (user.xp >= this.configExp.neededExpToTheNextLevel) {
                if (user.level < this.configExp.maxLevel) {
                    user.level++;
                    user.coins++;
                    user.xp = 0;
                    console.log(`User ${user.discordName} passed a level`);
                }
            }

            await user.save();
        } catch (error) {
            console.log('[giveExpToUserByMessage:error]', error);
        }
    }
}
